behaviors: 
  jankTest1:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings: 
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 5e6
    time_horizon: 64
    summary_freq: 10000
    threaded: false
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 50
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
